site_name: Cyclope Agent
site_url: https://promql-agent.qwerty.com.ar
repo_url: https://github.com/joagonzalez/cyclops-devops-agent/
edit_uri: edit/master/docs/

nav:
  - Agent: 
    - Overview: index.md
    - Application: agent.md
    - Endpoints: endpoints.md
    - Services: services.md
  - Tests: tests.md

theme:
  name: readthedocs
  features:
    - content.action.edit
    - content.action.view
    
plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          show_submodules: true

extra_css:
  - css/extra.css